import { PropertyListing } from "./types";
import Chalet from "../assets/chalet.jpg";
import desertDome from "../assets/desert eco dome.jpg";

export const listings: PropertyListing[] = [
  {
    id: "1",
    title: "Modern Loft in Downtown",
    description:
      "Stylish loft with amazing city views. Perfect for urban explorers.",
    price: 120,
    image: "https://images.app.goo.gl/8PVRSXHApeUAZThd8",
    rating: 4.92,
    reviews: 128,
    type: "Entire apartment",
    beds: 2,
    baths: 1,
    amenities: ["Wifi", "Kitchen", "Washer", "Air conditioning"],
    location: {
      city: "New York",
      country: "United States",
    },
    host: "Michael",
    superhost: true,
    dates: "Nov 12-18",
  },
  {
    id: "2",
    title: "Beachfront Villa with Pool",
    description:
      "Luxury villa steps from the beach with private infinity pool.",
    price: 350,
    image: "https://source.unsplash.com/random/800x600/?villa,beach",
    rating: 4.98,
    reviews: 87,
    type: "Entire villa",
    beds: 4,
    baths: 3,
    amenities: ["Pool", "Ocean view", "Private beach", "Gourmet kitchen"],
    location: {
      city: "Malibu",
      country: "United States",
    },
    host: "Sarah",
    superhost: true,
    dates: "Dec 1-7",
  },
  {
    id: "3",
    title: "Cozy Mountain Cabin",
    description: "Rustic cabin with fireplace and stunning mountain views.",
    price: 95,
    image: "https://source.unsplash.com/random/800x600/?cabin,mountain",
    rating: 4.85,
    reviews: 64,
    type: "Entire cabin",
    beds: 1,
    baths: 1,
    amenities: ["Fireplace", "Hiking trails", "Hot tub", "Pet friendly"],
    location: {
      city: "Aspen",
      country: "United States",
    },
    host: "David",
    superhost: false,
    dates: "Jan 5-12",
  },
  {
    id: "4",
    title: "Chic Parisian Studio",
    description:
      "Charming studio in the heart of Montmartre with Eiffel Tower views.",
    price: 135,
    image: "https://source.unsplash.com/random/800x600/?paris,apartment",
    rating: 4.79,
    reviews: 203,
    type: "Entire studio",
    beds: 1,
    baths: 1,
    amenities: ["Wifi", "Elevator", "Coffee maker", "City view"],
    location: {
      city: "Paris",
      country: "France",
    },
    host: "Sophie",
    superhost: true,
    dates: "Mar 15-22",
  },
  {
    id: "5",
    title: "Luxury Penthouse with Terrace",
    description: "Spacious penthouse with 360° city views and rooftop terrace.",
    price: 420,
    image: "https://source.unsplash.com/random/800x600/?penthouse,luxury",
    rating: 4.95,
    reviews: 56,
    type: "Entire penthouse",
    beds: 3,
    baths: 2,
    amenities: ["Terrace", "Gym", "Doorman", "Smart TV"],
    location: {
      city: "Miami",
      country: "United States",
    },
    host: "Carlos",
    superhost: true,
    dates: "Apr 3-9",
  },
  {
    id: "6",
    title: "Traditional Japanese Ryokan",
    description:
      "Authentic ryokan experience with tatami mats and onsen baths.",
    price: 180,
    image: "https://source.unsplash.com/random/800x600/?ryokan,japan",
    rating: 4.88,
    reviews: 142,
    type: "Entire ryokan",
    beds: 2,
    baths: 1,
    amenities: ["Onsen", "Yukata", "Tea ceremony", "Garden view"],
    location: {
      city: "Kyoto",
      country: "Japan",
    },
    host: "Yuki",
    superhost: true,
    dates: "May 10-17",
  },
  {
    id: "7",
    title: "Lakefront Cottage",
    description: "Quaint cottage with private dock and stunning sunsets.",
    price: 110,
    image: "https://source.unsplash.com/random/800x600/?cottage,lake",
    rating: 4.9,
    reviews: 78,
    type: "Entire cottage",
    beds: 2,
    baths: 1,
    amenities: ["Lake access", "Kayaks", "Fire pit", "Fishing gear"],
    location: {
      city: "Lake Tahoe",
      country: "United States",
    },
    host: "Emily",
    superhost: false,
    dates: "Jun 7-14",
  },
  {
    id: "8",
    title: "Historic London Flat",
    description: "Beautifully restored Victorian flat near major attractions.",
    price: 160,
    image: "https://source.unsplash.com/random/800x600/?london,flat",
    rating: 4.82,
    reviews: 189,
    type: "Entire flat",
    beds: 2,
    baths: 1,
    amenities: ["Wifi", "Washer", "Dishwasher", "Historical charm"],
    location: {
      city: "London",
      country: "United Kingdom",
    },
    host: "James",
    superhost: true,
    dates: "Jul 22-29",
  },
  {
    id: "9",
    title: "Desert Eco-Dome",
    description:
      "Unique geodesic dome with spectacular stargazing opportunities.",
    price: 130,
    image: desertDome,
    rating: 4.93,
    reviews: 112,
    type: "Entire dome",
    beds: 1,
    baths: 1,
    amenities: ["Stargazing", "Solar powered", "Outdoor shower", "Hammock"],
    location: {
      city: "Sedona",
      country: "United States",
    },
    host: "Aisha",
    superhost: true,
    dates: "Aug 15-21",
  },
  {
    id: "10",
    title: "Ski-in/Ski-out Chalet",
    description: "Luxury chalet with direct access to the slopes and hot tub.",
    price: 290,
    image: Chalet,
    rating: 4.97,
    reviews: 73,
    type: "Entire chalet",
    beds: 5,
    baths: 3,
    amenities: ["Hot tub", "Ski storage", "Fireplace", "Mountain view"],
    location: {
      city: "Whistler",
      country: "Canada",
    },
    host: "Pierre",
    superhost: true,
    dates: "Dec 10-17",
  },
];
